# Generated by Django 6.0.7 on 2026-08-08 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0026_cashregistersettings_cashsession_cashentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Xona nomi')),
                ('capacity', models.IntegerField(default=0, verbose_name="Sig'imi (0 = cheklanmagan)")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='duration_minutes',
            field=models.IntegerField(default=90, verbose_name='Dars davomiyligi (daqiqa)'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('contact', "Bog'lanish kerak"), ('active', 'Faol')], db_index=True, default='active', max_length=10, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='student',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Holat o'zgargan sana"),
        ),
        migrations.AddField(
            model_name='student',
            name='status_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Holat izohi'),
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Daraja nomi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('monthly_fee', models.IntegerField(default=0, verbose_name="Oylik to'lov (0 = kurs narxi)")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='register_withvue.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Kurs darajasi',
                'verbose_name_plural': 'Kurs darajalari',
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='register_withvue.courselevel', verbose_name='Daraja'),
        ),
        migrations.AddField(
            model_name='group',
            name='room_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='register_withvue.room', verbose_name="Xona (ro'yxatdan)"),
        ),
    ]
