# Generated by Django 6.0.7 on 2026-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0027_room_group_duration_minutes_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
