# Generated by Django 6.0.7 on 2026-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0028_student_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='geo_info',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Joylashuv'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
