# Generated by Django 6.0.7 on 2026-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0029_lead_geo_info_lead_ip_address_lead_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='device_info',
            field=models.CharField(blank=True, default='', help_text='Telefon/kompyuter · OS · Brauzer', max_length=120, verbose_name='Qurilma'),
        ),
        migrations.AddField(
            model_name='lead',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='lead',
            name='geo_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
    ]
