# Generated by Django 6.0.7 on 2026-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0030_lead_device_info_lead_geo_lat_lead_geo_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='device_extra',
            field=models.CharField(blank=True, default='', help_text='Ekran · vaqt zonasi · til (frontend yuboradi)', max_length=120, verbose_name="Qurilma qo'shimcha"),
        ),
    ]
